apiVersion: v1
kind: PersistentVolume
metadata:
  name: asiayo-pv
spec:
  storageClassName: asiayo-test
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"