apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asiayo-pvc
  namespace: asiayo
spec:
  storageClassName: asiayo-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi